# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lakshay Pandey
tagline:          'All who wander are not lost'
description:      'Personal page for Lakshay Pandey'
url:              http://hyde.getpoole.com
baseurl:          /
blog_url: /blog
photoblog_url: https://photoblog.lakshaypandey.com
contact_url: /contact
resume_url: /public/Lakshay_Pandey_Mar_2015.pdf

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
paginate_path: "blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
