# Dependencies
markdown:         redcarpet
highlighter:      pygments
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge


# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Lakshay Pandey
tagline:          'All who wander are not lost'
description:      'All who wander are not lost - The Lord of the Rings'
url:              http://hyde.getpoole.com
baseurl:          /
blog_url: /blog
photoblog_url: https://photoblog.lakshaypandey.com
contact_url: /contact
resume_url: /public/Lakshay_Pandey.pdf



author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo
gems: [jekyll-paginate, jekyll-gist]
paginate:         20
paginate_path: "blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
